name: server
description: EasyFinance API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.0
  supabase: ^2.0.8

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
